### ISSUE TITLE
Render View with Model

### ISSUE THREAD

**Issue by sml01** [RonenNess/Serverito#2]
Possible to have server.ServeHtmlPage(context, model, "index.html");

index.html will automatically generate view with model.

**Comment by RonenNess** [comment]
Hi @sml01 I'm not sure I understand what you're asking, are you asking if serverito supports  html templates like with Django for example that you can use variables inside the html?

Thanks

**Comment by sml01** [comment]
Hi, yes something like that. and Razor able to use model. 

For example, if I want to display field of model, model.displayName..

thanks

**Comment by RonenNess** [comment]
Thanks for the feedback, but Serverito's focus is to handle just networking. Templating is a whole other subject and should be a framework of its own. 

Edit: Sorry hit the button too soon :)
Anyway why not just using external lib for templating? Are you having problems integrating?
